export const SUBSCRIBERS = [
    {
        id: 1,
        name: 'Anamika Singh',
        age: 50,
        gender: 'Female',
        condition: 'Heart Disease',
        status: 'Cancelled',
        appointmentDate: '18th Oct 2025',
        time: '11:00 AM',
        healthScore: 75,
        summary: 'Shortness of breath for four months, progressively worsening.',
        image: null,
    },
    {
        id: 2,
        name: 'Rahul Verma',
        age: 45,
        gender: 'Male',
        condition: 'Diabetes',
        status: 'Scheduled',
        appointmentDate: '20th Oct 2025',
        time: '09:30 AM',
        healthScore: 82,
        summary: 'Regular checkup for diabetes management.',
        image: null,
    },
    {
        id: 3,
        name: 'Neha Sharma',
        age: 38,
        gender: 'Female',
        condition: 'Hypertension',
        status: 'Completed',
        appointmentDate: '15th Oct 2025',
        time: '04:00 PM',
        healthScore: 68,
        summary: 'Follow-up for hypertension medication adjustment.',
        image: null,
    },
    {
        id: 4,
        name: 'Amit Patel', // Changed duplicate name for clarity
        age: 42,
        gender: 'Male',
        condition: 'Hypertension',
        status: 'Completed',
        appointmentDate: '15th Oct 2025',
        time: '04:00 PM',
        healthScore: 68,
        summary: 'Routine blood pressure monitoring.',
        image: null,
    },
];
